Repository JEOLLOGA/JEOLLOGA-CLIENT, pull requests merged in 2025-01, with the labels that each got.

#18 [FIX] PR 템플릿 생성 오류
  .github/pull_request_template.md
Labels: 🍀FIX🍀

#14 [INIT] import 절대경로 설정
  package.json
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🪷INIT🪷

#11 [INIT] svgr 세팅
  package.json
  src/assets/svgs/index.ts
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: 🪷INIT🪷

#15 [INIT] prettier 초기세팅
  .prettierrc
  package.json
  yarn.lock
Labels: 🪷INIT🪷

#16 [INIT] eslint 설정
  eslint.config.js
  package.json
  src/App.tsx
  src/main.tsx
  src/queryClient.ts
  yarn.lock
Labels: 🪷INIT🪷

#20 [INIT] Vanilla-extract CSS 초기세팅, theme설정 (fonts,color)
  package.json
  src/App.tsx
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/main.tsx
  src/styles/fonts.css.ts
  src/styles/global.css.ts
  src/styles/reset.css.ts
  src/styles/theme.css.ts
  vite.config.ts
  yarn.lock
Labels: 🪷INIT🪷, 🎨STYLE🎨

#25 [D OCS] 서비스 소개, 스택, 컨벤션 리드미 작성
  README.md
Labels: 📄DOCS📄

#24 [CI/CD] github actions 워크플로우 추가
  .github/auto_assign.yml
  .github/workflows/auto-sync.yml
  eslint.config.js
  src/stories/Button.tsx
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
Labels: 🔧CI/CD🔧

#26 [INIT] 스토리북 세팅, 크로마틱 배포 자동화
  .github/workflows/chromatic.yml
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.css.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: 🪷INIT🪷

#29 [FEAT] theme 글꼴, 색상 추가
  src/styles/fonts.css.ts
  src/styles/theme.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#36 [FEAT] 페이지 버튼 공통 컴포넌트 구현
  .storybook/preview.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.css.ts
  src/components/common/button/pageBtn/pageBtn.css.ts
  src/components/common/button/pageBtn/pageBtn.tsx
  src/stories/Button.stories.ts
  src/stories/pageBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#42 [FEAT] 태그 컴포넌트 구현
  .storybook/preview.tsx
  src/components/common/tag/Tag.tsx
  src/components/common/tag/tag.css.ts
  src/stories/Tag.stories.ts
  src/styles/theme.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#50 [FEAT] 버튼 컴포넌트 구현
  src/assets/svgs/icn_back_black_left.svg
  src/assets/svgs/index.ts
  src/components/common/button/arrowBtn/ArrowBtn.tsx
  src/components/common/button/arrowBtn/arrowBtn.css.ts
  src/components/common/button/underlinedBtn/UnderlinedBtn.tsx
  src/components/common/button/underlinedBtn/underlinedBtn.css.ts
  src/components/common/tag/Tag.tsx
  src/components/common/tag/tag.css.ts
  src/components/curation/curationCard/CurationCard.tsx
  src/components/curation/curationCard/curationCard.css.ts
  src/stories/ArrowBtn.stories.ts
  src/stories/CurationCard.stories.ts
  src/stories/Tag.stories.ts
  src/stories/UnderlinedBtn.stories.ts
  src/styles/theme.css.ts
  tsconfig.app.tsbuildinfo
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#48 [FEAT] 검색바 컴포넌트 퍼블리싱
  src/components/searchBar/SearchBar.tsx
  src/components/searchBar/searchBar.css.ts
  src/stories/SearchBar.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#54 [FIX] 태그 컴포넌트 부활시키기
  src/components/common/tag/Tag.tsx
  src/components/common/tag/tag.css.ts
  src/stories/Tag.stories.ts
Labels: 🍀FIX🍀

#57 [FEAT] 페이지 하단 공통 버튼 호버 구현
  src/components/common/button/pageBottom/PageBottomBtn.tsx
  src/components/common/button/pageBottom/pageBottomBtn.css.ts
  src/components/common/button/pageBtn/PageBtn.tsx
  src/stories/pageBottomBtn.stories.ts
  src/stories/pageBtn.stories.ts
  src/styles/theme.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#45 [FEAT] 텍스트 버튼 공통 컴포넌트 구현
  src/assets/svgs/icn_paste.svg
  src/components/common/button/textBtn/TextBtn.tsx
  src/components/common/button/textBtn/textBtn.css.ts
  src/stories/textBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#61 [FEAT] 상세 정보 컴포넌트 구현
  src/components/common/detailInfo/DetailInfo.tsx
  src/components/common/detailInfo/detailInfo.css.ts
  src/stories/DetailInfo.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#64 [FEAT] 상세 페이지 제목 공통 컴포넌트 구현
  src/components/detailTitle/DetailTitle.tsx
  src/components/detailTitle/detailTitle.css.ts
  src/stories/DetailTitle.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#71 [FEAT] 헤더, 푸터 컴포넌트 퍼블리싱
  src/assets/images/logo_small.png
  src/assets/svgs/icn_divider.svg
  src/assets/svgs/index.ts
  src/assets/svgs/logo_small.svg
  src/assets/svgs/logo_xsmall.svg
  src/components/footer/Footer.tsx
  src/components/footer/footer.css.ts
  src/components/header/Header.tsx
  src/components/header/header.css.ts
  src/stories/Footer.stories.ts
  src/stories/Header.stories.ts
  src/styles/reset.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#76 [FEAT] InfoBtn 컴포넌트 구현
  src/components/common/button/infoBtn/InfoBtn.tsx
  src/components/common/button/infoBtn/infoBtn.css.ts
  src/stories/InfoBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#78 [FEAT] 리뷰 컴포넌트 구현
  src/components/card/reviewCard/cardInfo/CardInfo.tsx
  src/components/card/reviewCard/cardInfo/cardInfo.css.ts
  src/components/card/reviewCard/reviewCard/ReviewCard.tsx
  src/components/card/reviewCard/reviewCard/reviewCard.css.ts
  src/components/common/button/onboardingBtn/OnboardingBtn.tsx
  src/components/common/button/onboardingBtn/onboardingBtn.css.ts
  src/components/common/button/pageBottomBtn/PageBottomBtn.tsx
  src/components/common/button/pageBottomBtn/pageBottomBtn.css.ts
  src/stories/OnboardingButton.stories.ts
  src/stories/ReviewCard.stories.ts
  src/stories/pageBottomBtn.stories.ts
  tsconfig.app.tsbuildinfo
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#70 [FEAT] 위시카드 컴포넌트 구현
  src/assets/svgs/icn_flower_gray.svg
  src/assets/svgs/icn_flower_pink.svg
  src/assets/svgs/index.ts
  src/components/card/templeStayCard/InfoSection.css.ts
  src/components/card/templeStayCard/InfoSection.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/templeStayCard.css.ts
  src/components/common/icon/flowerIcon/FlowerIcon.tsx
  src/stories/TempleStayCard.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#72 [FEAT] PopularCard 컴포넌트 구현
  src/assets/svgs/index.ts
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/popularCard/RankBtn.tsx
  src/components/card/popularCard/popularCard.css.ts
  src/components/card/popularCard/rankBtn.css.ts
  src/components/footer/Footer.tsx
  src/stories/PopularCard.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#84 [FEAT] router 세팅
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/router/Router.tsx
  src/styles/global.css.ts
  yarn.lock
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#69 [FEAT] 상세페이지 스케쥴 컴포넌트 제작
  src/components/schedule/ScheduleCard.tsx
  src/components/schedule/scheduleCard.css.ts
  src/stories/ScheduleCard.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#79 [FEAT] ButtonBar 컴포넌트 퍼블리싱
  src/assets/svgs/icn_reset.svg
  src/components/common/button/buttonBar/ButtonBar.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/button/flowerBtn/FlowerBtn.tsx
  src/components/common/button/flowerBtn/flowerBtn.css.ts
  src/components/common/button/pageBottomBtn/PageBottomBtn.tsx
  src/components/common/button/textBtn/TextBtn.tsx
  src/components/common/button/textBtn/textBtn.css.ts
  src/components/common/icon/FlowerIcon.tsx
  src/stories/ButtonBar.stories.ts
  src/stories/FlowerBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#85 [FEAT] 마이페이지 퍼블리싱
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/components/common/button/infoBtn/infoBtn.css.ts
  src/components/footer/footer.css.ts
  src/components/userInfo/userInfo.css.ts
  src/components/userInfo/userInfo.tsx
  src/components/userInfo/userInfoContent/accountAction/AccountAction.tsx
  src/components/userInfo/userInfoContent/accountAction/accountAction.css.ts
  src/components/userInfo/userInfoContent/helpContent/HelpContent.tsx
  src/components/userInfo/userInfoContent/helpContent/helpContent.css.ts
  src/components/userInfo/userInfoContent/nameContent/NameContent.tsx
  src/components/userInfo/userInfoContent/nameContent/nameContent.css.ts
  src/components/userInfo/userInfoContent/userDetailInfo.tsx/UserDetailInfo.tsx
  src/components/userInfo/userInfoContent/userDetailInfo.tsx/userDetailInfo.css.ts
  src/components/userInfo/userInfoContent/userInfoSection/userInfoSection.css.ts
  src/components/userInfo/userInfoContent/userInfoSection/userInfoSection.tsx
  src/constants/userInfo.ts
  src/hooks/useNavigateTo.tsx
  src/pages/myPage/MyPage.tsx
  src/router/Router.tsx
  src/stories/MyPage.stories.ts
  src/styles/global.css.ts
  yarn.lock
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#75 [FEAT] 페이지네이션 컴포넌트 구현
  src/assets/svgs/icn_linearrow_small_left.svg
  src/assets/svgs/icn_linearrow_small_right.svg
  src/components/common/button/pageBtn/PageBtn.tsx
  src/components/common/button/pageBtn/pageBtn.css.ts
  src/components/common/pagination/Pagination.tsx
  src/components/common/pagination/pagination.css.ts
  src/constants/constants.ts
  src/stories/Pagination.stories.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#91 [FEAT] 템플스테이 세부정보 컴포넌트 퍼블리싱
  src/components/templeDetail/templeInfo/contentCollapse/ContentCollapse.tsx
  src/components/templeDetail/templeInfo/contentCollapse/contentCollapse.css.ts
  src/components/templeDetail/templeInfo/templeInfo.css.ts
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/hooks/useExpandHook/useExpandHook.tsx
  src/stories/TempleInfo.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#94 [FEAT] 홈페이지 템플스테이 둘러보기 버튼 구현
  .storybook/preview.tsx
  package.json
  src/assets/images/home_card_look.png
  src/assets/svgs/icn_linearrow_large_right.svg
  src/components/card/lookCard/LookCard.tsx
  src/components/card/lookCard/lookCard.css.ts
  src/components/common/button/basicBtn/BasicBtn.tsx
  src/components/common/button/basicBtn/basicBtn.css.ts
  src/stories/BasicBtn.stories.ts
  src/stories/LookCard.stories.ts
  src/styles/theme.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#99 [FEAT] 홈페이지 지도 퍼블리싱
  src/assets/images/home_card_map.png
  src/assets/svgs/icn_double_arrow_lightgray_down.svg
  src/assets/svgs/index.ts
  src/components/card/mapCard/LocBtn.tsx
  src/components/card/mapCard/Map.tsx
  src/components/card/mapCard/MapCard.tsx
  src/components/card/mapCard/locBtn.css.ts
  src/components/card/mapCard/map.css.ts
  src/components/card/mapCard/mapCard.css.ts
  src/components/common/button/basicBtn/basicBtn.css.ts
  src/constants/regionInfos.ts
  src/stories/MapCard.stories.ts
  src/styles/theme.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#111 [FEAT] 위시리스트 페이지 퍼블리싱
  .gitignore
  src/App.tsx
  src/assets/images/img_gray_light_leaf_large.png
  src/components/card/templeStayCard/InfoSection.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/infoSection.css.ts
  src/components/card/templeStayCard/templeStayCard.css.ts
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/card/templeStayCard/wishCardList/wishCardList.css.ts
  src/components/common/empty/wishEmpty/WishEmpty.tsx
  src/components/common/empty/wishEmpty/wishEmpty.css.ts
  src/components/common/pagination/pagination.css.ts
  src/pages/wishList/WishListPage.tsx
  src/pages/wishList/wishListPage.css.ts
  src/router/Router.tsx
  src/stories/WishListPage.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#112 [FEAT] 로그인 페이지 퍼블리싱
  .gitignore
  src/assets/images/img_pink_light_smile.png
  src/assets/images/img_yellow_light_smile.png
  src/assets/svgs/icn_kakao_logo.svg
  src/assets/svgs/index.ts
  src/components/common/button/kakaoBtn/KakaoBtn.tsx
  src/components/common/button/kakaoBtn/kakaoBtn.css.ts
  src/constants/loginInfos.ts
  src/pages/WishPage.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/loginPage/loginPage.css.ts
  src/router/PrivateRoute.tsx
  src/router/Router.tsx
  src/stories/KakaoBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#97 [FEAT] 네이버 지도 컴포넌트 퍼블리싱
  .storybook/preview-head.html
  index.html
  package.json
  src/assets/images/icn_map.png
  src/assets/images/logo_small.png
  src/components/templeDetail/naverMap/MapContainer.tsx
  src/components/templeDetail/naverMap/largeMap/LargeMap.tsx
  src/components/templeDetail/naverMap/largeMap/largeMap.css.ts
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/naverMap/smallMap/smallMap.css.ts
  src/react-app-env.d.ts
  src/stories/LargeMap.stories.ts
  src/stories/SmallMap.stories.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#123 [FIX] 필요없는 storybook 파일 삭제 및 vercel 설정
  .storybook/preview.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vercel.json
Labels: 🍀FIX🍀

#110 [FEAT] 검색 필터 페이지 퍼블리싱
  .gitignore
  src/components/common/divider/Divider.tsx
  src/components/common/divider/divider.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/common/pageName/pageName.css.ts
  src/components/common/pagination/Pagination.tsx
  src/components/common/tapBar/TapBar.tsx
  src/components/common/tapBar/tapBar.css.ts
  src/components/filter/filterBox/FilterBox.tsx
  src/components/filter/filterBox/filterBox.css.ts
  src/components/filter/priceSlider/PriceSlider.tsx
  src/components/filter/priceSlider/priceSlider.css.ts
  src/constants/constants.ts
  src/constants/filters.ts
  src/hooks/useMoveScroll.ts
  src/hooks/useScrollTrack.tsx
  src/pages/filterPage/FilterPage.tsx
  src/pages/filterPage/filterPage.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/wishList/WishListPage.tsx
  src/router/Router.tsx
  src/stories/FilterBox.stories.tsx
  src/stories/PageName.stories.ts
  src/stories/filterPage.stories.ts
  src/styles/global.css.ts
  src/type/titleMap.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#118 [FEAT] axios 기본 설정
  src/apis/instance.ts
  src/apis/messages.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#116 [FEAT] 메인페이지 퍼블리싱
  src/components/card/lookCard/lookCard.css.ts
  src/components/card/mapCard/map.css.ts
  src/components/card/mapCard/mapCard.css.ts
  src/components/carousel/curationCarousel/curationCarousel.css.ts
  src/components/carousel/popularCarousel/carouselIndex.css.ts
  src/components/footer/footer.css.ts
  src/pages/HomePage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/homePage.css.ts
  src/router/Router.tsx
  src/stories/HomePage.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#130 [FEAT] 온보딩 퍼블리싱
  src/assets/images/img_login_finish.png
  src/components/common/button/onboardingBtn/OnboardingBtn.tsx
  src/components/common/button/onboardingBtn/onboardingBtn.css.ts
  src/components/common/progressBar/ProgressBar.tsx
  src/components/common/progressBar/progressBar.css.ts
  src/components/onboarding/ExperienceBtn.tsx
  src/components/onboarding/OnboardingSection.tsx
  src/components/onboarding/onboardingSection.css.ts
  src/constants/onboarding/onboardingSteps.ts
  src/constants/onboarding/registerOptions.ts
  src/pages/onboardingPage/OnboardingPage.tsx
  src/pages/onboardingPage/onboardingPage.css.ts
  src/pages/welcomePage/WelcomePage.tsx
  src/pages/welcomePage/welcomePage.css.ts
  src/router/Router.tsx
  src/stories/OnboardingPage.stories.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#128 [FEAT] 상세페이지 사찰 이미지 캐러셀 구현
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/carousel/detailCarousel/detailCarousel.css.ts
  src/components/carousel/detailCarousel/numberTag/NumberTag.tsx
  src/hooks/useCarousel.ts
  src/stories/DetailCarousel.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#115 [FEAT] 모달 컴포넌트 퍼블리싱
  src/components/common/button/popupBtn/PopupBtn.tsx
  src/components/common/button/popupBtn/popup.css.ts
  src/components/common/modal/BtnBox.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/common/modal/modal.css.ts
  src/stories/ModalContainer.stories.ts
  src/stories/PopupBtn.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#127 [FIX] 메인에서 이미지 안 보이는 이슈 해결
  src/constants/loginInfos.ts
  src/pages/loginPage/loginPage.css.ts
Labels: 🍀FIX🍀

#135 [FEAT] 큐레이션 상세 페이지 구현
  src/assets/images/curations/cmp_card_curation_beginner_thumbnail.png
  src/assets/images/curations/cmp_card_curation_bonginsa_thumbnail.png
  src/assets/images/curations/cmp_card_curation_doglover_thumbnail.png
  src/assets/images/curations/cmp_card_curation_popular_thumbnail.png
  src/assets/images/curations/curation_beginner_1.png
  src/assets/images/curations/curation_beginner_2.png
  src/assets/images/curations/curation_beginner_3.png
  src/assets/images/curations/curation_beginner_4.png
  src/assets/images/curations/curation_bonginsa_1.png
  src/assets/images/curations/curation_bonginsa_2.png
  src/assets/images/curations/curation_bonginsa_3.png
  src/assets/images/curations/curation_bonginsa_4.png
  src/assets/images/curations/curation_doglover_1.png
  src/assets/images/curations/curation_doglover_2.png
  src/assets/images/curations/curation_doglover_3.png
  src/assets/images/curations/curation_doglover_4.png
  src/assets/images/curations/curation_popular_1.png
  src/assets/images/curations/curation_popular_2.png
  src/assets/images/curations/curation_popular_3.png
  src/assets/images/curations/curation_popular_4.png
  src/components/carousel/curationCarousel/CurationCarousel.tsx
  src/components/curation/curationCard/curationCard.css.ts
  src/constants/curationInfo.ts
  src/pages/CurationPage.tsx
  src/router/Router.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#140 [FIX] ux 라이팅 수정
  src/components/card/lookCard/LookCard.tsx
  src/components/common/button/kakaoBtn/KakaoBtn.tsx
  src/components/common/empty/wishEmpty/WishEmpty.tsx
  src/components/search/searchBar/SearchBar.tsx
  src/constants/loginInfos.ts
  src/constants/onboarding/onboardingSteps.ts
  src/constants/onboarding/registerOptions.ts
  src/pages/homePage/HomePage.tsx
Labels: 🍀FIX🍀

#137 [FEAT] 템플스테이 상세 페이지 구현
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/common/pageName/PageName.tsx
  src/components/common/tapBar/TapBar.tsx
  src/components/detailTitle/DetailTitle.tsx
  src/components/templeDetail/naverMap/largeMap/largeMap.css.ts
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/naverMap/smallMap/smallMap.css.ts
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/stickyTapBar/stickyTapBar.css.ts
  src/components/templeDetail/templeDetailInfo/TempleDetailInfo.tsx
  src/components/templeDetail/templeDetailInfo/templeDetailInfo.css.ts
  src/components/templeDetail/templeInfo/templeInfo.css.ts
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/components/templeDetail/templePrice/TemplePrice.tsx
  src/components/templeDetail/templePrice/templePrice.css.ts
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeReview/templeReview.css.ts
  src/components/templeDetail/templeSchedule/TempleSchedule.tsx
  src/components/templeDetail/templeSchedule/templeSchedule.css.ts
  src/components/templeDetail/templeTitle/TempleTitle.tsx
  src/components/templeDetail/templeTitle/templeTitle.css.ts
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/components/templeDetail/templeTopbar/templeTopbar.css.ts
  src/constants/templeDetail.ts
  src/constants/templePhoto.ts
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/blogReview/blogReviewPage.css.ts
  src/pages/templeDetailPage/templeDetailPage.css.ts
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
  src/pages/wishList/WishListPage.tsx
  src/router/Router.tsx
  src/stories/DetailTitle.stories.ts
  src/stories/TempleDetailPage.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#144 [FEAT] 카카오 로그인 api 연결
  src/apis/auth/axios.ts
  src/apis/auth/index.ts
  src/apis/auth/type.ts
  src/apis/instance.ts
  src/components/common/button/kakaoBtn/KakaoBtn.tsx
  src/components/userInfo/userInfo.tsx
  src/pages/RedirectionPage/RedirectionPage.tsx
  src/router/PrivateRoute.tsx
  src/router/Router.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#132 [FEAT] 이번주 인기 스테이 불러오기 api 연결
  src/apis/ranking/axios.ts
  src/apis/ranking/index.ts
  src/apis/ranking/type.ts
  src/components/carousel/popularCarousel/PopularCarousel.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#149 [FEAT] 사용자 닉네임 반환, 온보딩 정보 전송 api 연결
  src/apis/user/axios.ts
  src/apis/user/index.ts
  src/apis/user/type.ts
  src/pages/homePage/HomePage.tsx
  src/pages/onboardingPage/OnboardingPage.tsx
  src/pages/welcomePage/WelcomePage.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#154 [FIX] 자잘한 수정사항 반영 완료
  src/components/curation/curationCard/curationCard.css.ts
  src/components/footer/Footer.tsx
Labels: 🍀FIX🍀

#148 [FEAT] 위시리스트 api 연결
  src/apis/wish/axios.ts
  src/apis/wish/index.ts
  src/apis/wish/type.ts
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/header/Header.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/wishList/WishListPage.tsx
  src/stories/PopularCard.stories.ts
  src/stories/TempleStayCard.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#152 [FEAT] 최근 검색어 리스트 반환, 삭제 api 연결
  src/apis/search/axios.ts
  src/apis/search/index.ts
  src/apis/search/type.ts
  src/components/detailTitle/DetailTitle.tsx
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/searchPage.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#155 [FEAT] 이미지 로티로 변경
  package.json
  src/assets/lotties/home.lottie
  src/assets/lotties/moktak_hit.lottie
  src/assets/lotties/moktak_sad.lottie
  src/assets/lotties/onboarding.lottie
  src/assets/lotties/pink_light_smile.lottie
  src/assets/lotties/tree_fall.lottie
  src/assets/lotties/yellow_light_smile.lottie
  src/components/card/lookCard/LookCard.tsx
  src/components/card/lookCard/lookCard.css.ts
  src/components/common/empty/filterEmpty/FilterEmpty.tsx
  src/components/common/empty/filterEmpty/filterEmpty.css.ts
  src/components/common/empty/searchEmpty/SearchEmpty.tsx
  src/components/common/empty/searchEmpty/searchEmpty.css.ts
  src/components/except/exceptLayout/ExceptLayout.tsx
  src/constants/exceptInfos.ts
  src/constants/loginInfos.ts
  src/main.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/welcomePage/WelcomePage.tsx
  src/pages/welcomePage/welcomePage.css.ts
  src/react-app-env.d.ts
  src/router/Router.tsx
  yarn.lock
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#142 [FEAT] 마이페이지 api 연결
  src/apis/myPage/axios.ts
  src/apis/myPage/index.ts
  src/apis/myPage/type.ts
  src/components/footer/Footer.tsx
  src/components/userInfo/userInfo.tsx
  src/constants/userInfo.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.css.ts
  tsconfig.app.tsbuildinfo
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#158 [FEAT] 블로그 리뷰 api 연결
  src/apis/auth/index.ts
  src/apis/templeReviews/axios.ts
  src/apis/templeReviews/index.ts
  src/apis/templeReviews/type.ts
  src/assets/svgs/icn_empty_image.svg
  src/assets/svgs/index.ts
  src/components/card/reviewCard/cardInfo/CardInfo.tsx
  src/components/card/reviewCard/reviewCard/ReviewCard.tsx
  src/components/card/reviewCard/reviewCard/reviewCard.css.ts
  src/components/detailTitle/DetailTitle.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeReview/templeReview.css.ts
  src/pages/searchPage/SearchPage.tsx
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/router/Router.tsx
  tsconfig.app.tsbuildinfo
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#167 [FEAT] privateinstance, Instance 나눠서 분기처리 로직 구현
  src/apis/filter/axios.ts
  src/apis/instance.ts
  src/apis/ranking/axios.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#168 [FIX] 로티 key 추가 및 홈페이지 헤더 아이콘 수정
  src/components/card/lookCard/LookCard.tsx
  src/components/common/empty/filterEmpty/FilterEmpty.tsx
  src/components/common/empty/searchEmpty/SearchEmpty.tsx
  src/components/except/exceptLayout/ExceptLayout.tsx
  src/components/header/Header.tsx
  src/components/header/header.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/welcomePage/WelcomePage.tsx
Labels: 🍀FIX🍀

#146 [FEAT] 템플스테이 이미지 url api 연결
  src/apis/templeImages/axios.ts
  src/apis/templeImages/index.ts
  src/apis/templeImages/type.ts
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/pageName/pageName.css.ts
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/userInfo/userInfo.tsx
  src/hooks/useNavigateTo.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#162 [FIX] 캐러셀 인덱스 수정
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/carousel/popularCarousel/popularCarousel.css.ts
  src/pages/homePage/HomePage.tsx
Labels: 🍀FIX🍀

#176 [FIX] 마이페이지 수정사항 반영
  src/apis/myPage/axios.ts
  src/apis/myPage/index.ts
  src/apis/myPage/type.ts
  src/apis/user/axios.ts
  src/apis/user/index.ts
  src/apis/user/type.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/common/modal/modal.css.ts
  src/components/userInfo/userInfo.css.ts
  src/components/userInfo/userInfo.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.css.ts
  src/pages/onboardingPage/OnboardingPage.tsx
Labels: 🍀FIX🍀

#177 [FIX] 검색어 localstorage로 관리하는 로직 추가 및 기타등등 ... 이것저것 ...
  src/apis/auth/index.ts
  src/apis/search/index.ts
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/search/recentBtn/recentBtnBox.css.ts
  src/hooks/useFilter.ts
  src/pages/CurationPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/searchPage.css.ts
  src/type/type.ts
Labels: 🍀FIX🍀

#181 [FIX] 로티 절대경로로 변경
  public/lotties/home.lottie
  public/lotties/moktak_hit.lottie
  public/lotties/moktak_sad.lottie
  public/lotties/onboarding.lottie
  public/lotties/pink_light_smile.lottie
  public/lotties/tree_fall.lottie
  public/lotties/yellow_light_smile.lottie
  src/components/card/lookCard/LookCard.tsx
  src/components/common/empty/filterEmpty/FilterEmpty.tsx
  src/components/common/empty/searchEmpty/SearchEmpty.tsx
  src/constants/exceptInfos.ts
  src/constants/loginInfos.ts
  src/pages/welcomePage/WelcomePage.tsx
Labels: 🍀FIX🍀

#179 [FEAT] 위시 추가 삭제 연결
  src/apis/wish/index.ts
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/common/button/buttonBar/ButtonBar.tsx
  src/components/common/button/flowerBtn/FlowerBtn.tsx
  src/components/common/pageName/PageName.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/pages/RedirectionPage/RedirectionPage.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/pages/wishList/WishListPage.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#182 [FEAT] 첫 로그인한 유저인 경우 온보딩 페이지로 이동 로직 구현
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/apis/user/index.ts
  src/components/card/lookCard/LookCard.tsx
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/onboardingPage/OnboardingPage.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#184 [FIX] 인기스테이 상세 페이지 이동
  src/apis/instance.ts
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
Labels: 🍀FIX🍀

#185 [DEPLOY] dev to main
  public/lotties/home.lottie
  public/lotties/moktak_hit.lottie
  public/lotties/moktak_sad.lottie
  public/lotties/onboarding.lottie
  public/lotties/pink_light_smile.lottie
  public/lotties/tree_fall.lottie
  public/lotties/yellow_light_smile.lottie
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/apis/myPage/axios.ts
  src/apis/myPage/index.ts
  src/apis/myPage/type.ts
  src/apis/search/index.ts
  src/apis/templeDetail/index.ts
  src/apis/user/axios.ts
  src/apis/user/index.ts
  src/apis/user/type.ts
  src/apis/wish/index.ts
  src/components/card/lookCard/LookCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/common/button/buttonBar/ButtonBar.tsx
  src/components/common/button/flowerBtn/FlowerBtn.tsx
  src/components/common/empty/filterEmpty/FilterEmpty.tsx
  src/components/common/empty/searchEmpty/SearchEmpty.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/common/modal/modal.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/search/recentBtn/recentBtnBox.css.ts
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/components/userInfo/userInfo.css.ts
  src/components/userInfo/userInfo.tsx
  src/constants/exceptInfos.ts
  src/constants/loginInfos.ts
  src/hooks/useFilter.ts
  src/main.tsx
  src/pages/CurationPage.tsx
  src/pages/HomePage.tsx
  src/pages/RedirectionPage/RedirectionPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.css.ts
  src/pages/onboardingPage/OnboardingPage.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/searchPage.css.ts
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/pages/welcomePage/WelcomePage.tsx
  src/pages/wishList/WishListPage.tsx
  src/type/type.ts
Labels: 😎deploy😎

#188 [FEAT] getAxiosInstance 필요한 부분 적용
  src/apis/templeDetail/axios.ts
  src/apis/templeDetail/index.ts
  src/components/common/pageName/PageName.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#189 [FIX] 이것저것
  src/components/card/templeStayCard/infoSection.css.ts
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/pages/homePage/homePage.css.ts
Labels: 🍀FIX🍀

#190 [DEPLOY] dev to main
  src/apis/templeDetail/axios.ts
  src/apis/templeDetail/index.ts
  src/components/card/templeStayCard/infoSection.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/pages/homePage/homePage.css.ts
  src/pages/templeDetailPage/TempleDetailPage.tsx
Labels: 😎deploy😎

#195 [FEAT] 비로그인 위시 클릭 시 로그인 연결
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/modal/modal.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/homePage.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/searchResultPage/searchResultPage.css.ts
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/stories/PopularCarousel.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲, 🍀FIX🍀

#197 [DEPLOY] dev to main
  index.html
  src/assets/images/img_gray_light_leaf_medium.png
  src/assets/images/img_gray_light_leaf_small.png
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/reviewCard/reviewCard/ReviewCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/card/templeStayCard/templeStayCard.css.ts
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/carousel/detailCarousel/detailCarousel.css.ts
  src/components/carousel/detailCarousel/numberTag/NumberTag.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/modal/modal.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/hooks/useNavigateTo.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/homePage.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/searchResultPage/searchResultPage.css.ts
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/stories/PopularCarousel.stories.ts
  src/styles/global.css.ts
Labels: 😎deploy😎

#198 [FIX] 큐레이션 탑바 상단 고정, 캐러셀 감도 조절
  src/hooks/useCarousel.ts
  src/pages/CurationPage/CurationPage.tsx
  src/pages/CurationPage/curationPage.css.ts
  src/router/Router.tsx
Labels: 🍀FIX🍀

#203 [FIX] QA 대응
  src/components/common/pageName/PageName.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/homePage.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/router/PrivateRoute.tsx
Labels: 🍀FIX🍀

#204 [FIX] 상세페이지 QA 반영
  src/components/card/templeStayCard/templeStayCard.css.ts
  src/components/templeDetail/naverMap/MapContainer.tsx
  src/components/templeDetail/naverMap/largeMap/LargeMap.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeInfo/templeInfo.css.ts
  src/components/templeDetail/templePrice/templePrice.css.ts
  src/components/templeDetail/templeReview/templeReview.css.ts
  src/components/templeDetail/templeSchedule/templeSchedule.css.ts
  src/hooks/useCarousel.ts
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/styles/reset.css.ts
Labels: 🍀FIX🍀

#202 [FEAT] 모달 후 연결되는 로그인페이지 생성
  src/components/common/modal/Modal.tsx
  src/components/userInfo/userInfo.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/loginPage/ModalLoginPage.tsx
  src/pages/loginPage/modalLoginPage.css.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.css.ts
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/router/Router.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#205 [DEPLOY] dev to main
  src/components/card/lookCard/LookCard.tsx
  src/components/card/templeStayCard/templeStayCard.css.ts
  src/components/common/modal/Modal.tsx
  src/components/common/pageName/PageName.tsx
  src/components/detailTitle/DetailTitle.tsx
  src/components/detailTitle/detailTitle.css.ts
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/templeDetail/naverMap/MapContainer.tsx
  src/components/templeDetail/naverMap/largeMap/LargeMap.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeInfo/templeInfo.css.ts
  src/components/templeDetail/templePrice/templePrice.css.ts
  src/components/templeDetail/templeReview/templeReview.css.ts
  src/components/templeDetail/templeSchedule/templeSchedule.css.ts
  src/components/userInfo/userInfo.tsx
  src/constants/curationInfo.ts
  src/hooks/useCarousel.ts
  src/hooks/useFilter.ts
  src/pages/CurationPage/CurationPage.tsx
  src/pages/CurationPage/curationPage.css.ts
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/homePage.css.ts
  src/pages/loginPage/LoginPage.tsx
  src/pages/loginPage/ModalLoginPage.tsx
  src/pages/loginPage/modalLoginPage.css.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.css.ts
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/router/PrivateRoute.tsx
  src/router/Router.tsx
  src/styles/reset.css.ts
Labels: 😎deploy😎

#210 [FIX] 검색 QA 반영
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/search/searchBar/searchBar.css.ts
  src/hooks/useFilter.ts
Labels: 🍀FIX🍀

#212 [FIX] 엑세스 토큰 재요청 로직 수정
  src/apis/instance.ts
  src/apis/user/axios.ts
  src/components/filter/filterTypeBox/FilterTypeBox.tsx
  src/hooks/useFilter.ts
  src/pages/welcomePage/WelcomePage.tsx
Labels: 🍀FIX🍀

#213 [DEPLOY] dev to main
  public/lotties/moktak_hit.lottie
  public/lotties/tree_fall.lottie
  src/apis/instance.ts
  src/apis/user/axios.ts
  src/components/filter/filterTypeBox/FilterTypeBox.tsx
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/search/searchBar/searchBar.css.ts
  src/hooks/useFilter.ts
  src/pages/welcomePage/WelcomePage.tsx
  src/router/Router.tsx
Labels: 😎deploy😎

#216 [FIX] 새로고침 해야 데이터 갱신되는 문제 해결 및 로딩, 에러화면 추가
  src/apis/search/index.ts
  src/components/search/recentBtn/RecentBtnBox.tsx
Labels: 🍀FIX🍀

#215 [FIX] 상세페이지 2차
  src/components/carousel/curationCarousel/CurationCarousel.tsx
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/common/detailInfo/detailInfo.css.ts
  src/components/common/tapBar/TapBar.tsx
  src/components/filter/filterTypeBox/filterTypeBox.css.ts
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/components/templeDetail/templePrice/TemplePrice.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeSchedule/TempleSchedule.tsx
  src/components/templeDetail/templeTitle/TempleTitle.tsx
  src/components/templeDetail/templeTitle/templeTitle.css.ts
  src/components/templeDetail/templeTopbar/templeTopbar.css.ts
  src/hooks/useMoveScroll.ts
  src/pages/searchResultPage/searchResultPage.css.ts
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/blogReview/blogReviewPage.css.ts
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
Labels: 🍀FIX🍀

#217 [DEPLOY] dev to main
  src/apis/search/index.ts
  src/components/carousel/curationCarousel/CurationCarousel.tsx
  src/components/carousel/detailCarousel/DetailCarousel.tsx
  src/components/carousel/detailCarousel/DetailImage.tsx
  src/components/common/detailInfo/detailInfo.css.ts
  src/components/common/tapBar/TapBar.tsx
  src/components/filter/filterTypeBox/filterTypeBox.css.ts
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/components/templeDetail/templePrice/TemplePrice.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeSchedule/TempleSchedule.tsx
  src/components/templeDetail/templeTitle/TempleTitle.tsx
  src/components/templeDetail/templeTitle/templeTitle.css.ts
  src/components/templeDetail/templeTopbar/templeTopbar.css.ts
  src/hooks/useMoveScroll.ts
  src/pages/searchResultPage/searchResultPage.css.ts
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/blogReview/blogReviewPage.css.ts
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
Labels: 😎deploy😎

#221 [DEPLOY] dev to main
  src/components/common/empty/wishEmpty/WishEmpty.tsx
Labels: 😎deploy😎

#223 [DEPLOY] dev to main
  src/styles/global.css.ts
Labels: 😎deploy😎

#224 [FIX] QA 3차 대응
  src/components/common/modal/modal.css.ts
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/searchResultPage/searchResultPage.css.ts
Labels: 🍀FIX🍀

#225 [DEPLOY] dev to main
  src/components/common/modal/modal.css.ts
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/searchResultPage/searchResultPage.css.ts
Labels: 😎deploy😎

#220 [DOCS] readme 서비스 기능 추가 및 최신화
  README.md
Labels: 📄DOCS📄

#229 [FEAT] ga 붙이기
  index.html
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#230 [FIX] 온보딩 하단 버튼 위치 조정
  src/pages/onboardingPage/OnboardingPage.tsx
  src/pages/onboardingPage/onboardingPage.css.ts
Labels: 🍀FIX🍀

#232 [FIX] QA 4차반영
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/schedule/scheduleCard.css.ts
  src/pages/wishList/WishListPage.tsx
Labels: 🍀FIX🍀

#234 [FIX] QA 4차 반영
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
  src/pages/wishList/WishListPage.tsx
  src/pages/wishList/wishListPage.css.ts
Labels: 🍀FIX🍀

#235 [DEPLOY] dev to main
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/schedule/scheduleCard.css.ts
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
  src/pages/wishList/WishListPage.tsx
  src/pages/wishList/wishListPage.css.ts
Labels: 😎deploy😎

#237 [FIX] QA 5차 대응
  src/components/common/tapBar/TapBar.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/components/templeDetail/templePrice/TemplePrice.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeSchedule/TempleSchedule.tsx
  src/hooks/useMoveScroll.ts
Labels: 🍀FIX🍀

#238 [DEPLOY] dev to main
  src/components/common/tapBar/TapBar.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/templeInfo/templeInfo.tsx
  src/components/templeDetail/templePrice/TemplePrice.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/templeDetail/templeSchedule/TempleSchedule.tsx
  src/hooks/useMoveScroll.ts
Labels: 😎deploy😎

#239 [FIX] 가격 슬라이드 로직 수정
  src/components/filter/priceSlider/PriceSlider.tsx
  src/hooks/debounce.ts
  src/hooks/useFilter.ts
Labels: 🍀FIX🍀

#240 [DEPLOY] dev to main
  src/components/filter/priceSlider/PriceSlider.tsx
  src/hooks/debounce.ts
  src/hooks/useFilter.ts
Labels: 😎deploy😎
