Repository JEOLLOGA/JEOLLOGA-CLIENT, pull requests merged in 2025-03, with the labels that each got.

#251 [CI/CD] vercel preview 배포 전용 workflow 추가
  .github/workflows/auto-sync.yml
  .github/workflows/deploy-preview.yml
Labels: 🔧CI/CD🔧

#256 [CI/CD] preview가 아닌 production으로 배포되는 문제 해결하기
  .github/workflows/deploy-preview.yml
Labels: 🍀FIX🍀, 🔧CI/CD🔧

#247 [REFACTOR] 로그인 리팩토링
  src/apis/auth/axios.ts
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/pages/RedirectionPage/RedirectionPage.tsx
Labels: ⚙️REFACTOR⚙️

#246 [FEAT] robots.txt 및 메타태그 정보 추가
  index.html
  robots.txt
  sitemap.xml
  src/components/card/lookCard/LookCard.tsx
  src/components/card/lookCard/lookCard.css.ts
  src/components/card/mapCard/MapCard.tsx
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/carousel/curationCarousel/CurationCarousel.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/curation/curationCard/CurationCard.tsx
  src/components/detailTitle/DetailTitle.tsx
  src/pages/wishList/WishListPage.tsx
  src/stories/CurationCard.stories.ts
  src/stories/PopularCard.stories.ts
  src/stories/TempleStayCard.stories.ts
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#257 [DEPLOY] dev to main
  .github/workflows/auto-sync.yml
  .github/workflows/deploy-preview.yml
  index.html
  robots.txt
  sitemap.xml
  src/apis/auth/axios.ts
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/components/card/lookCard/LookCard.tsx
  src/components/card/lookCard/lookCard.css.ts
  src/components/card/mapCard/MapCard.tsx
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
  src/components/card/templeStayCard/wishCardList/WishCardList.tsx
  src/components/carousel/curationCarousel/CurationCarousel.tsx
  src/components/carousel/popularCarousel/PopularCarousel.tsx
  src/components/curation/curationCard/CurationCard.tsx
  src/components/detailTitle/DetailTitle.tsx
  src/pages/RedirectionPage/RedirectionPage.tsx
  src/pages/wishList/WishListPage.tsx
  src/stories/CurationCard.stories.ts
  src/stories/PopularCard.stories.ts
  src/stories/TempleStayCard.stories.ts
  vercel.json
Labels: 😎deploy😎

#259 [FIX] robots.txt, sitemap.xml 파일 경로 수정
  index.html
  public/robots.txt
  public/sitemap.xml
Labels: 🍀FIX🍀

#243 [REFACTOR] 상세페이지 탭바, 페이지 이동 리팩토링
  src/App.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/common/tapBar/TapBar.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/constants/constants.ts
  src/hooks/useMoveScroll.ts
  src/hooks/useNavigateTo.tsx
  src/hooks/useScrollToTop.ts
  src/pages/CurationPage/CurationPage.tsx
  src/pages/filterPage/FilterPage.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/wishList/WishListPage.tsx
  src/stories/PageName.stories.ts
Labels: ⚙️REFACTOR⚙️

#263 [FIX] 템플스테이 카드 위시리스트 담기 클릭시 페이지 이동 막기 구현
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
Labels: 🍀FIX🍀

#265 [FEAT] 탈퇴하기 api 연결
  src/apis/auth/axios.ts
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/pages/myPage/MyPage.tsx
Labels: 👩🏻‍🦲FEAT👩🏻‍🦲

#266 [DEPLOY] dev to main
  index.html
  public/robots.txt
  public/sitemap.xml
  src/App.tsx
  src/apis/auth/axios.ts
  src/apis/auth/index.ts
  src/apis/instance.ts
  src/components/card/popularCard/PopularCard.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/common/button/basicBtn/BasicBtn.tsx
  src/components/common/button/buttonBar/buttonBar.css.ts
  src/components/common/pageName/PageName.tsx
  src/components/common/tapBar/TapBar.tsx
  src/components/search/recentBtn/RecentBtnBox.tsx
  src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
  src/components/templeDetail/templeTopbar/TempleTopbar.tsx
  src/constants/constants.ts
  src/hooks/useCarousel.ts
  src/hooks/useFilter.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useMoveScroll.ts
  src/hooks/useNavigateTo.tsx
  src/hooks/useScrollToTop.ts
  src/pages/CurationPage/CurationPage.tsx
  src/pages/filterPage/FilterPage.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
  src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
  src/pages/wishList/WishListPage.tsx
  src/stories/PageName.stories.ts
Labels: 😎deploy😎

#269 [DEPLOY] dev to main
  src/components/card/lookCard/LookCard.tsx
  src/components/card/mapCard/Map.tsx
  src/components/card/templeStayCard/TempleStayCard.tsx
  src/components/common/button/kakaoBtn/KakaoBtn.tsx
  src/components/common/empty/wishEmpty/WishEmpty.tsx
  src/components/common/tapBar/TapBar.tsx
  src/components/footer/Footer.tsx
  src/components/search/searchBar/SearchBar.tsx
  src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
  src/components/templeDetail/templeReview/TempleReview.tsx
  src/components/userInfo/userInfo.tsx
  src/constants/regionInfos.ts
  src/gtm/GTMProvider.tsx
  src/gtm/hooks/useEventLogger.ts
  src/gtm/types.ts
  src/gtm/window.d.ts
  src/hooks/useExpandHook/useExpandHook.tsx
  src/main.tsx
  src/pages/filterPage/FilterPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/onboardingPage/OnboardingPage.tsx
  src/pages/searchResultPage/SearchResultPage.tsx
  src/pages/templeDetailPage/TempleDetailPage.tsx
  src/pages/welcomePage/WelcomePage.tsx
Labels: 😎deploy😎
